### ISSUE TITLE
[BUG] Getting node stats from AWS instance fails with: Missing required property 'DataPathStats.mount'

### ISSUE THREAD

**Issue by fs-chris** [opensearch-project/opensearch-java#1341]
### What is the bug?
Getting node-stats from an OpenSearch instance running as AWS service fails with the following exception.
```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'DataPathStats.mount'
	at deployment.app//org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:90)
	at deployment.app//org.opensearch.client.opensearch.nodes.DataPathStats.<init>(DataPathStats.java:69)
	at deployment.app//org.opensearch.client.opensearch.nodes.DataPathStats.<init>(DataPathStats.java:50)
	at deployment.app//org.opensearch.client.opensearch.nodes.DataPathStats$Builder.build(DataPathStats.java:230)
	at deployment.app//org.opensearch.client.opensearch.nodes.DataPathStats$Builder.build(DataPathStats.java:159)
	at deployment.app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:98)
	at deployment.app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:60)
	at deployment.app//org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:343)
	at deployment.app//org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:308)
	at deployment.app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:81)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:185)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:146)
	at deployment.app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:91)
	at deployment.app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:55)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:81)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:185)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:146)
	at deployment.app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:91)
	at deployment.app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:55)
	at deployment.app//org.opensearch.client.json.JsonpDeserializerBase$StringMapDeserializer.deserialize(JsonpDeserializerBase.java:369)
	at deployment.app//org.opensearch.client.json.JsonpDeserializerBase$StringMapDeserializer.deserialize(JsonpDeserializerBase.java:355)
	at deployment.app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:81)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:185)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:146)
	at deployment.app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:91)
	at deployment.app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:55)
	at deployment.app//org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:360)
	at deployment.app//org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:326)
	at deployment.app//org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:148)
	at deployment.app//org.opensearch.client.opensearch.nodes.OpenSearchNodesClient.stats(OpenSearchNodesClient.java:205)
	at deployment.app//org.opensearch.client.opensearch.nodes.OpenSearchNodesClient.stats(OpenSearchNodesClient.java:219)
```

### How can one reproduce the bug?
Connect the client to an AWS service instance of OpenSearch.
Execute a request like: `client.nodes().stats(s -> s.metric("fs"))`

### What is the expected behavior?
The client should be able to parse the partial result returned from the AWS instance.

### What is your host/environment?
Java client 2.18.0
OpenSearch server 2.13/2.17 (tested both) hosted on AWS

### Do you have any screenshots?
`GET _nodes/stats?metric=fs`
Sample response from AWS (left) vs. local on-prem instance.

![image](https://github.com/user-attachments/assets/b6c40288-bcb9-4a92-a337-4177300d112b)

### Do you have any additional context?
n/a

**Comment by fs-chris** [comment]
A similar issue happens with  `client.cluster().stats()`
```
Caused by: org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'ClusterOperatingSystemName.name'
	at deployment.app//org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:89)
	at deployment.app//org.opensearch.client.opensearch.cluster.stats.ClusterOperatingSystemName.<init>(ClusterOperatingSystemName.java:60)
	at deployment.app//org.opensearch.client.opensearch.cluster.stats.ClusterOperatingSystemName.<init>(ClusterOperatingSystemName.java:50)
	at deployment.app//org.opensearch.client.opensearch.cluster.stats.ClusterOperatingSystemName$Builder.build(ClusterOperatingSystemName.java:137)
	at deployment.app//org.opensearch.client.opensearch.cluster.stats.ClusterOperatingSystemName$Builder.build(ClusterOperatingSystemName.java:107)
	at deployment.app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:98)
	at deployment.app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:60)
	at deployment.app//org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:343)
	at deployment.app//org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:308)
	at deployment.app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:81)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:185)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:146)
	at deployment.app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:91)
	at deployment.app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:55)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:81)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:185)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:146)
	at deployment.app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:91)
	at deployment.app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:55)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:81)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:185)
	at deployment.app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:146)
	at deployment.app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:91)
	at deployment.app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:55)
	at deployment.app//org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:360)
	at deployment.app//org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:326)
	at deployment.app//org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:148)
	at deployment.app//org.opensearch.client.opensearch.cluster.OpenSearchClusterClient.stats(OpenSearchClusterClient.java:673)
```

**Comment by Xtansia** [comment]
This was fixed as part of v2.23.0 of the client
