### ISSUE TITLE
[BUG] Deserializing ChildrenAggregate is broken

### ISSUE THREAD

**Issue by siva-unravel** [opensearch-project/opensearch-java#305]
### What is the bug?
Deserializing ChildrenAggregate in the SearchResponse is broken.

The following error is being thrown.
```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'ChildrenAggregate.buckets'
```
### How can one reproduce the bug?
Write a ChildAggregation in the SearchRequest
```
 Aggregation aggregation = Aggregation.of(b -> b
                .children(cb -> cb
                        .type("child")
                )
);
SearchResponse<Doc> searchResponse = client.search(b -> b
                        .index(Index)
                        .query(query)
                        .aggregations("aggs", aggregation)
                , Doc.class
);
```

The following error is being thrown
```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'ChildrenAggregate.buckets'

	at org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:88)
	at org.opensearch.client.opensearch._types.aggregations.MultiBucketAggregateBase.<init>(MultiBucketAggregateBase.java:64)
	at org.opensearch.client.opensearch._types.aggregations.ChildrenAggregate.<init>(ChildrenAggregate.java:54)
	at org.opensearch.client.opensearch._types.aggregations.ChildrenAggregate.<init>(ChildrenAggregate.java:50)
	at org.opensearch.client.opensearch._types.aggregations.ChildrenAggregate$Builder.build(ChildrenAggregate.java:94)
	at org.opensearch.client.opensearch._types.aggregations.ChildrenAggregate$Builder.build(ChildrenAggregate.java:76)
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:93)
	at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56)
	at org.opensearch.client.json.ExternallyTaggedUnion$Deserializer.deserialize(ExternallyTaggedUnion.java:77)
	at org.opensearch.client.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserializeEntry(ExternallyTaggedUnion.java:118)
	at org.opensearch.client.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserialize(ExternallyTaggedUnion.java:101)
	at org.opensearch.client.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserialize(ExternallyTaggedUnion.java:89)
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88)
	at org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:85)
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:189)
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:150)
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88)
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:92)
	at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56)
	at org.opensearch.client.transport.endpoints.EndpointWithResponseMapperAttr$1.deserialize(EndpointWithResponseMapperAttr.java:69)
	at org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:320)
	at org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:286)
	at org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:143)
	at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1219)
	at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1234)

```
### What is the expected behavior?
Children Aggregation is single bucket aggregation, so I am not expecting multiple buckets

### What is your host/environment?
version
```
opensearch server 2.3.0
opensearch-java 1.0.0
opensearch-rest-client 1.3.2
```

Am I missing something?

**Comment by wbeckler** [comment]
This looks worth fixing. Feel free to submit a PR for a fix or a failing test.
