### ISSUE TITLE
[BUG] Unhelpful error message when failing to authenticate with Amazon OpenSearch Service

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/opensearch-java#473]
### What is the bug?
This is related to our opensearch sink use case with Amazon OpenSearch backend sts role authentication: https://github.com/opensearch-project/data-prepper/issues/2655

### How can one reproduce the bug?
When sts role is not configured with the right permissions, one gets
```
[security_exception] authentication/authorization failure
```

### What is the expected behavior?
Ideally the [cause message](https://github.com/opensearch-project/opensearch-java/blob/af8d96fc34373542b2332efa3b258f754de33de6/java-client/src/main/java/org/opensearch/client/transport/aws/AwsSdk2Transport.java#L453) could be

1. more specific about the operation that fails authentication
2. print the sts role used in authentication

### What is your host/environment?
all

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
What's the actual HTTP response for this?

Looking at [the code](https://github.com/opensearch-project/opensearch-java/blob/e422eb0263847bd1ca867c8c109bbb15463fae5b/java-client/src/main/java/org/opensearch/client/transport/aws/AwsSdk2Transport.java#L452-L453) it does try to parse the response and pull out the complete message.

**Comment by chenqi0805** [comment]
@dblock Sorry for the late response. I also had a hard time to reproduce it. But it is with getClusterSettings:
```
org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [security_exception] authentication/authorization failure
	at org.opensearch.client.transport.aws.AwsSdk2Transport.parseResponse(AwsSdk2Transport.java:517) ~[opensearch-java-2.2.0.jar:?]
	at org.opensearch.client.transport.aws.AwsSdk2Transport.executeSync(AwsSdk2Transport.java:438) ~[opensearch-java-2.2.0.jar:?]
	at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:241) ~[opensearch-java-2.2.0.jar:?]
	at org.opensearch.client.opensearch.cluster.OpenSearchClusterClient.getSettings(OpenSearchClusterClient.java:282) ~[opensearch-java-2.2.0.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.index.AbstractIndexManager.checkISMEnabled(AbstractIndexManager.java:187) ~[opensearch-2.2.1.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.index.AbstractIndexManager.checkAndCreateIndexTemplate(AbstractIndexManager.java:208) ~[opensearch-2.2.1.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.index.AbstractIndexManager.setupIndex(AbstractIndexManager.java:203) ~[opensearch-2.2.1.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.doInitializeInternal(OpenSearchSink.java:174) ~[opensearch-2.2.1.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.doInitialize(OpenSearchSink.java:139) ~[opensearch-2.2.1.jar:?]
	at org.opensearch.dataprepper.model.sink.SinkThread.run(SinkThread.java:23) ~[data-prepper-api-2.2.1.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```
but for some reason when I try to call the API with the wrong role, it does yield clear message:
```
Exception in thread "main" org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [security_exception] User: arn:aws:sts::531516510575:assumed-role/FullAccess/qchea-Isengard is not authorized to perform: es:ESHttpGet because no resource-based policy allows the es:ESHttpGet action
	at org.opensearch.client.transport.aws.AwsSdk2Transport.parseResponse(AwsSdk2Transport.java:517)
	at org.opensearch.client.transport.aws.AwsSdk2Transport.executeSync(AwsSdk2Transport.java:438)
	at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:241)
	at org.opensearch.client.opensearch.cluster.OpenSearchClusterClient.getSettings(OpenSearchClusterClient.java:282)
```
This seems to be a corner case failed to be covered. Is it possible that the fine-grained access control of Amazon OpenSearch might cause missing response message be overriden?

**Comment by dblock** [comment]
Yes, it's possible. First, try to do this with `awscurl` or `curl`, see the responses and how different they are?

**Comment by chenqi0805** [comment]
@dblock I was able to reproduce the issue with FGAC domain that the client does not have proper permission/role. It seems we should be parsing `reason` in this scenario instead of `message` or `Message`. Let me know if you have suggestions on the fix.

![Screenshot 2023-05-22 at 9 37 02 AM](https://github.com/opensearch-project/opensearch-java/assets/19492223/57e1b336-3890-4241-9470-6c463560712d)
