### ISSUE TITLE
[BUG] org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'MultiSearchItem.status'

### ISSUE THREAD

**Issue by javiermorant** [opensearch-project/opensearch-java#520]
### What is the bug?
multi search is not working with multisearch template but it does with regular multisearch using programatic query.
Error :
msearchTemplate() throws MissingRequiredPropertyException

```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'MultiSearchItem.status'
	at org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:88)
	at org.opensearch.client.opensearch.core.msearch.MultiSearchItem.<init>(MultiSearchItem.java:62)
	at org.opensearch.client.opensearch.core.msearch.MultiSearchItem$Builder.build(MultiSearchItem.java:119)
	at org.opensearch.client.opensearch.core.msearch.MultiSearchItem$Builder.build(MultiSearchItem.java:92)
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:99)
	at org.opensearch.client.json.UnionDeserializer$SingleMemberHandler.deserialize(UnionDeserializer.java:91)
	at org.opensearch.client.json.UnionDeserializer.deserialize(UnionDeserializer.java:324)
	at org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:353)
	at org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:322)
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88)
	at org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:85)
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:189)
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:150)
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88)
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:92)
	at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56)
	at org.opensearch.client.transport.endpoints.EndpointWithResponseMapperAttr$1.deserialize(EndpointWithResponseMapperAttr.java:69)
	at org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:325)
	at org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:291)
	at org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:144)
	at org.opensearch.client.opensearch.OpenSearchClient.msearchTemplate(OpenSearchClient.java:960)
```

### How can one reproduce the bug?
perform a multisearch openSearchClient.msearchTemplate() method

### What is the expected behavior?
Expected behavior is that there is a 200 response from opensearch with the results ready to be parsed

### What is your host/environment?
local docker with opensearch version 2.5.0 running in Mac Os using java client from kotlin

### Do you have any additional context?
Same issue was reported to elastic search here: 
https://github.com/elastic/elasticsearch-java/issues/110
and solved here:
https://github.com/elastic/elasticsearch-java/commit/4a0aa0826d73f5cb593b1c4a34346b02c3d15263

**Comment by dblock** [comment]
@javiermorant Clear bug, thanks for reporting. Interested in making a PR to fix this? Please make sure to not bring in/looking at any non-APLv2 code.

**Comment by Xtansia** [comment]
Looks to be a really simple fix, just making `status` optional in https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/core/msearch/MultiSearchItem.java

- Change type of `status` from `int` to `Integer`
- Add `@Nullable` annotations
- Remove `ApiTypeHelper.requireNonNull` check in constructor
- Wrap serialization of `status` in `if (this.status != null) {}`
