### ISSUE TITLE
[BUG] "Misspelling" on setting maxAnalyzedOffset from Highlight.Builder

### ISSUE THREAD

**Issue by alexsandrospecht** [opensearch-project/opensearch-java#553]
### What is the bug?
We have a "misspelling" on the maxAnalyzedOffset setting from `Highlight.Builder`. [here](https://github.com/opensearch-project/opensearch-java/blob/852553075a363d2c397e7cd8d645a6b3af42cf06/java-client/src/main/java/org/opensearch/client/opensearch/core/search/Highlight.java#L301)

When we set the `maxAnalyzedOffset` in the `Highlight.Builder` the setting that is added on the json is `max_analyzed_offset` (looks right but it's not), when we execute this query we get the following error:
```
    "error": {
        "root_cause": [
            {
                "type": "x_content_parse_exception",
                "reason": "[36:9] [highlight] unknown field [max_analyzed_offset] did you mean [max_analyzer_offset]?"
            }
        ],
        "type": "x_content_parse_exception",
        "reason": "[36:9] [highlight] unknown field [max_analyzed_offset] did you mean [max_analyzer_offset]?"
    },
    "status": 400
}
```

The `max_analyzed_offset` setting is from [ElasticSearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html), on OpenSearch the correct setting is `max_analyzer_offset`.

### How can one reproduce the bug?
```
final var openSearchRequest = new SearchRequest.Builder()
                    .trackTotalHits(t -> t.enabled(true))
                    .index(indexReadAlias)
                    .query(queryBuilder.buildQuery())
                    .highlight(builder -> builder
                            .preTags(preTag)
                            .postTags(postTag)
                            .maxAnalyzedOffset(MAX_ANALYZER_OFFSET) <- Just need to set this 
                            .fields(Document.TITLE_FIELD, buildHighlightField())
                            .fields(Document.CONTENT_FIELD, buildHighlightField())
                            .fields(Document.URL_FIELD, buildHighlightField()))
                    .size(queryBuilder.querySize())
                    .from(queryBuilder.startFrom())
                    .sort(sortBuilder.buildSort())
                    .build();
```

### What is the expected behavior?
Update the api to match the OpenSearch Highlight setting `max_analyzer_offset`

### What is your host/environment?
Amazon OpenSearch service 2.5 managed by AWS.

### Do you have any additional context?
StackTrace:
```
19:00:59.853 [http-nio-auto-1-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [x_content_parse_exception] [1:637] [highlight] unknown field [max_analyzed_offset] did you mean [max_analyzer_offset]?] with root cause
org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [x_content_parse_exception] [1:637] [highlight] unknown field [max_analyzed_offset] did you mean [max_analyzer_offset]?
	at org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:278)
	at org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:144)
	at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1302)
	...
```

**Comment by szczepanczykd** [comment]
@schmittjoaopedro You can use SNAPSHOT from there:
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/opensearch-java/2.6.0-SNAPSHOT/

An example maven config:

```
<properties>
        <opensearch.java.version>2.6.0-20230705.163620-8</opensearch.java.version>
</properties>
```

```
        <dependency>
            <groupId>org.opensearch.client</groupId>
            <artifactId>opensearch-java</artifactId>
            <version>${opensearch.java.version}</version>
        </dependency>
```

```
<repositories>
        <repository>
            <id>opensearch snapshots</id>
            <url>https://aws.oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
</repositories>
```

**Comment by schmittjoaopedro** [comment]
Thanks

**Comment by alexsandrospecht** [comment]
Thank you
