### ISSUE TITLE
[BUG] RestClientTransport throws NoSuchMethodError

### ISSUE THREAD

**Issue by andrewparmet** [opensearch-project/opensearch-java#631]
### What is the bug?
RestClientTransport is unusable:

```
java.lang.NoSuchMethodError: 'void org.opensearch.client.Request.setEntity(org.apache.hc.core5.http.HttpEntity)'
  at org.opensearch.client.transport.rest_client.RestClientTransport.prepareLowLevelRequest(RestClientTransport.java:221)
  at org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:148)
  at org.opensearch.client.opensearch.indices.OpenSearchIndicesClient.create(OpenSearchIndicesClient.java:244)
  at org.opensearch.client.opensearch.indices.OpenSearchIndicesClient.create(OpenSearchIndicesClient.java:258)
```

Using latest HEAD - `d09bb4e`.

### How can one reproduce the bug?
Use the RestClientTransport.

### What is the expected behavior?
Requests should work.

### What is your host/environment?
Mac OS.

### Do you have any screenshots?
Nope.

### Do you have any additional context?
Nope.

**Comment by reta** [comment]
Please check https://github.com/opensearch-project/opensearch-java/blob/main/USER_GUIDE.md#creating-a-client, the `RestClientTransport` is deprecated in 3.0.0.
