### ISSUE TITLE
MissingRequiredPropertyException: Missing required property 'Stats.adaptiveSelection'

### ISSUE THREAD

**Issue by fs-chris** [opensearch-project/opensearch-java#740]
### What is the bug?
The `_nodes/stats` API is not usable because the response cannot be parsed.
It fails with the following error.

```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'Stats.adaptiveSelection'
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:89)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.util.ApiTypeHelper.unmodifiableRequired(ApiTypeHelper.java:207)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.opensearch.nodes.Stats.<init>(Stats.java:99)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.opensearch.nodes.Stats$Builder.build(Stats.java:743)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.opensearch.nodes.Stats$Builder.build(Stats.java:380)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:92)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:55)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.JsonpDeserializerBase$StringMapDeserializer.deserialize(JsonpDeserializerBase.java:369)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.JsonpDeserializerBase$StringMapDeserializer.deserialize(JsonpDeserializerBase.java:355)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:81)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:185)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:146)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:91)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:55)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:317)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:283)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:143)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.opensearch.nodes.OpenSearchNodesClient.stats(OpenSearchNodesClient.java:205)
	at deployment.njams-6.1.0-SNAPSHOT.war//org.opensearch.client.opensearch.nodes.OpenSearchNodesClient.stats(OpenSearchNodesClient.java:219)
...
```

### How can one reproduce the bug?
E.g.  `client.nodes().stats(s -> s.metric("fs"))`

### What is the expected behavior?
The API should not throw an error.

### What is your host/environment?
OpenSearch 2.11.0
Java client 2.8.1
Java 17

### Do you have any screenshots?
./.

### Do you have any additional context?
./.

**Comment by Bfindlay** [comment]
PR https://github.com/opensearch-project/opensearch-java/pull/745
